# Tarea semana 01:


## Ambientes virtuales en python

Para instalar un ambiente virtual en python, en primer lugar hay que instalar pip (una herramienta que se utiliza para descargar paquetes del repositorio Pypi) con el comando python3 -m pip install --user --upgrade pip, luego se sigue con la instalación de virtualenv (permite la gestión y la creación de entornos virtuales) con el comando python3 -m pip install --user virtualenv. Después de haber instaldo ambas herramientas ya se pueden crear ambientes virtuales con el comando python3 -m venv env, donde env es el nombre que se le quiere dar al ambiente virtual. 

## Manejo de proyecto en github

Para el manejo de un proyecto en github se necesita instalar git, luego se utilizaran los siguientes comandos:

- git init
- git status -s
- git commit -m "comentario"
- git add . 
- git push 
- git remote add origin pagina

Con el comando git init se inicia un repositorio local el cual irá guardando todos los cambios que se realicen al proyecto, luego tenemos git status -s, este comando nos indicará que cambios han sido guardados en el repositorio y los que no lo hayan sido se agregan con el comando git add ., ya que este comando agrega al repositorio temporal todos los cambios, para finalmente con el comando git commit -m agregar los cambios al repositorio local además de un breve comentario que describa el cambio que se hizo. Para github tenemos los comandos git remote add origin pagina, el cual indica donde se guardara el repositorio en la nube, y el comando git push que llevará todos los cambios realizados en el repositorio local al nuevo repositorio de la nube.

## Librerias

### Numpy

La librería numPy nos da una nueva estructura para almacenar datos como lo son las matrices, además de proporcionar operaciones matemáticas basicas para esta nueva estructura, como se puede ver en el siguiente ejemplo:

In [1]:
import numpy as np 

In [12]:
A = np.array( [[1, 2, 3], [3, 4, 5], [5, 6, 7]] )
print ("Matriz A:")
print (A)
print ("\n A al cuadrado:")
print (np.dot(A,A))



Matriz A:
[[1 2 3]
 [3 4 5]
 [5 6 7]]

 A al cuadrado:
[[22 28 34]
 [40 52 64]
 [58 76 94]]


## Pandas