# Tarea semana 01:


## Ambientes virtuales en python

Para instalar un ambiente virtual en python, en primer lugar hay que instalar pip (una herramienta que se utiliza para descargar paquetes del repositorio Pypi) con el comando python3 -m pip install --user --upgrade pip, luego se sigue con la instalación de virtualenv (permite la gestión y la creación de entornos virtuales) con el comando python3 -m pip install --user virtualenv. Después de haber instaldo ambas herramientas ya se pueden crear ambientes virtuales con el comando python3 -m venv env, donde env es el nombre que se le quiere dar al ambiente virtual. 

## Manejo de proyecto en github

Para el manejo de un proyecto en github se necesita instalar git, luego se utilizaran los siguientes comandos:

- git init
- git status -s
- git commit -m "comentario"
- git add . 
- git push 
- git remote add origin pagina

Con el comando git init se inicia un repositorio local el cual irá guardando todos los cambios que se realicen al proyecto, luego tenemos git status -s, este comando nos indicará que cambios han sido guardados en el repositorio y los que no lo hayan sido se agregan con el comando git add ., ya que este comando agrega al repositorio temporal todos los cambios, para finalmente con el comando git commit -m agregar los cambios al repositorio local además de un breve comentario que describa el cambio que se hizo. Para github tenemos los comandos git remote add origin pagina, el cual indica donde se guardara el repositorio en la nube, y el comando git push que llevará todos los cambios realizados en el repositorio local al nuevo repositorio de la nube.

## Librerias

### Numpy

La librería NumPy nos da una nueva estructura para almacenar datos como lo son las matrices, además de proporcionar operaciones matemáticas basicas para esta nueva estructura, como se puede ver en el siguiente ejemplo:

In [2]:
#importamos la librería
import numpy as np 

In [3]:
#crea matriz A de 3x3
A = np.array( [[1, 2, 3], [3, 4, 5], [5, 6, 7]] )

#imprime por pantalla la matriz A
print ("Matriz A:")
print (A)

#Eleva al cuadrado la matriz A
print ("\n A al cuadrado:")
print (np.dot(A,A))



Matriz A:
[[1 2 3]
 [3 4 5]
 [5 6 7]]

 A al cuadrado:
[[22 28 34]
 [40 52 64]
 [58 76 94]]


## Pandas

La librería panda nos entrega estructuras flexibles y expresivas para trabajar con datos etiquetados, como lo son las series, además de proporcionar operaciones y herramientas para el manejo de estos datos como tambien nos aporta un manejo sencillo de las fechas, todo lo anterior se puede ver en el siguiente ejemplo:

In [4]:
#importamos la librería 
import pandas as pd

In [22]:
#creamos una serie de datos
serie_ejemplo = pd.Series(range(10), index = list('abcdefghij'))

#imprime la serie por pantalla
print("Serie: ")
print(serie_ejemplo)

#máximo de la serie 
print("\nMáximo:")
print(serie_ejemplo.max())
print("su índice es: ")
print(serie_ejemplo[serie_ejemplo == max(serie_ejemplo)])

#creamos serie de fechas
fechas_ejemplo = pd.date_range(start = '10/1/2019', end = '10/31/2019' , freq = 'D')

#imprimimos por pantalla la serie de fechas
print("\nSerie de fechas:")
print(fechas_ejemplo)


Serie: 
a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int64

Máximo:
9
su índice es: 
j    9
dtype: int64

Serie de fechas:
DatetimeIndex(['2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04',
               '2019-10-05', '2019-10-06', '2019-10-07', '2019-10-08',
               '2019-10-09', '2019-10-10', '2019-10-11', '2019-10-12',
               '2019-10-13', '2019-10-14', '2019-10-15', '2019-10-16',
               '2019-10-17', '2019-10-18', '2019-10-19', '2019-10-20',
               '2019-10-21', '2019-10-22', '2019-10-23', '2019-10-24',
               '2019-10-25', '2019-10-26', '2019-10-27', '2019-10-28',
               '2019-10-29', '2019-10-30', '2019-10-31'],
              dtype='datetime64[ns]', freq='D')


## Matplotlib